name: CI

# we can specify which github events will trigger a CI build
on: push

# now define a single job 'build' (but could define more)
jobs:

  builds:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    # we can also specify the OS to run tests on
    runs-on: ${{ matrix.os }}

    # a job is a seq of steps
    steps:

    # Next we need to checkout repository and set up Python
    # A 'name' is an optional label shown in the log - helpful to clarify progress
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python depedencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Test with PyTest
      run: |
        python -m pytest --cov=inflammation.models tests/test_models.py